### ISSUE TITLE
JavaScript quizzes show Falcon stacktrace on submit

### ISSUE THREAD

**Issue by forbiddenvoid** [udacity/falcon#5]
If a quiz is submitted without a semicolon at the end of the last line, an error is raised that is displayed to the student with the full Falcon stacktrace:

![screen shot 2017-11-10 at 1 55 36 pm](https://user-images.githubusercontent.com/4620576/32680306-e2427114-c61e-11e7-80dc-010dafd056bd.png)
![screen shot 2017-11-10 at 1 55 48 pm](https://user-images.githubusercontent.com/4620576/32680309-e4986d1a-c61e-11e7-8bdb-54b340c09697.png)

**Comment by forbiddenvoid** [comment]
@cameronwp @jarrodparkes: I've isolated this to a problem that occurs when the swizzle files and student file are swizzled together. CDs have been writing the main function inside of `swizzleAfter.js` as an IIFE, which causes issues if the last statement of the student's file isn't a semicolon. 

I think a simple solution would be to write a single semicolon into the outfile after each file has been written during that process. Right now CDs have been getting around this by adding a single semicolon to the beginning of the `swizzleAfter.js` file.

I can make the change if you're cool with it, but I'm open to other options for this as well.

**Comment by cameronwp** [comment]
Go for it!
